# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGYarTQDlBCoWcxVfsG8HY3fZ74Z4VDF
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect('/content/Digital_payment_methods.db')

df2 = pd.read_sql('SELECT * FROM Digital_payment_methods', conn)
#table_name based on the table name you selected when you created the db
conn.close()


df2.head()





# Display information about columns and data types
print(df2.info())

#Finding the missing values in each column
print(df2.isna().sum())

# prompt: count duplicated raws

duplicate_rows_df2 = df2[df2.duplicated()]
print(f"Number of duplicated rows: {len(duplicate_rows_df2)}")

# Removing Duplicates

df2.drop_duplicates(inplace = True)

# Display information about columns and data types
print(df2.info())

# Checking Duplicates
print(df2.duplicated())

import pandas as pd

# Read csv file
df1 = pd.read_csv("digital payment methods Cleaned.csv")

print(df1.shape)
print(df3.shape)

df_concat=pd.concat([df1,df2],axis=0)

df_concat.shape

df_concat.to_csv('final digital payment methods.csv', index=False)