# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SS8GVOmEQoWjZKk4E-Lgj1KFO_tmpuqe
"""

import pandas as pd

# Read csv file
df = pd.read_csv("modified_csv_with_problems.csv")

# Display the first ten lines
print(df.head())

#Check the datatype for each column
 print(df.dtypes)

# Display information about columns and data types
print(df.info())

# Descriptive statistics
print(df.describe())

#Finding the missing values in each column
print(df.isna().sum())

# Checking Duplicates
print(df.duplicated())

# prompt: count duplicated raws

duplicate_rows_df = df[df.duplicated()]
print(f"Number of duplicated rows: {len(duplicate_rows_df)}")

# Removing Duplicates

df.drop_duplicates(inplace = True)

# Checking Duplicates
print(df.duplicated())

# prompt: count duplicated raws

duplicate_rows_df = df[df.duplicated()]
print(f"Number of duplicated rows: {len(duplicate_rows_df)}")

print(df.isna().sum())

df.dtypes

#Using replace method
df['payment_method'] = df['payment_method'].replace('UPI', 'Unified Payments Interface')

# Print Specific columns in csv file
df['payment_method']

print(df.isna().sum())

#filling nan value
df.loc[df['merchant_name'] == 'Mumbai Water', 'product_category'] = 'Water Bill'
df.loc[df['merchant_name'] == 'Bangalore Water Supply', 'product_category'] = 'Water Bill'
df.loc[df['merchant_name'] == 'Chennai Metro Water', 'product_category'] = 'Water Bill'
df.loc[df['merchant_name'] == 'Delhi Jal Board', 'product_category'] = 'Water Bill'
df.loc[df['merchant_name'] == 'Hyderabad Water Board', 'product_category'] = 'Water Bill'
#############################################################################################
df.loc[df['merchant_name'] == 'Adani Gas', 'product_category'] = 'Gas Bill'
df.loc[df['merchant_name'] == 'Bharat Gas', 'product_category'] = 'Gas Bill'
df.loc[df['merchant_name'] == 'Gujarat Gas', 'product_category'] = 'Gas Bill'
df.loc[df['merchant_name'] == 'Indraprastha Gas', 'product_category'] = 'Gas Bill'
df.loc[df['merchant_name'] == 'Mahanagar Gas', 'product_category'] = 'Gas Bill'
######################################################################################3
df.loc[df['merchant_name'] == 'Amazon Pay', 'product_category'] = 'Gift Card'
df.loc[df['merchant_name'] == 'Flipkart', 'product_category'] = 'Gift Card'
df.loc[df['merchant_name'] == 'Lifestyle', 'product_category'] = 'Gift Card'
df.loc[df['merchant_name'] == 'Pantaloons', 'product_category'] = 'Gift Card'
df.loc[df['merchant_name'] == 'Shoppers Stop', 'product_category'] = 'Gift Card'
####################################################################################
df.loc[df['merchant_name'] == 'Amazon Pantry', 'product_category'] = 'Grocery Shopping'
df.loc[df['merchant_name'] == 'BigBasket', 'product_category'] = 'Grocery Shopping'
df.loc[df['merchant_name'] == 'Flipkart Supermart', 'product_category'] = 'Grocery Shopping'
df.loc[df['merchant_name'] == 'Grofers', 'product_category'] = 'Grocery Shopping'
df.loc[df['merchant_name'] == "Nature's Basket", 'product_category'] = 'Grocery Shopping'
##########################################################################################
df.loc[df['merchant_name'] == 'Airbnb', 'product_category'] = 'Hotel Booking'
df.loc[df['merchant_name'] == 'Fab Hotels', 'product_category'] = 'Hotel Booking'
df.loc[df['merchant_name'] == 'MakeMyTrip', 'product_category'] = 'Hotel Booking'
df.loc[df['merchant_name'] == 'OYO Rooms', 'product_category'] = 'Hotel Booking'
df.loc[df['merchant_name'] == 'Treebo', 'product_category'] = 'Hotel Booking'
##################################################################################
df.loc[df['merchant_name'] == 'HDFC Life', 'product_category'] = 'Insurance Premium'
df.loc[df['merchant_name'] == 'ICICI Prudential', 'product_category'] = 'Insurance Premium'
df.loc[df['merchant_name'] == 'LIC', 'product_category'] = 'Insurance Premium'
df.loc[df['merchant_name'] == 'Max Life', 'product_category'] = 'Insurance Premium'
df.loc[df['merchant_name'] == 'SBI Life', 'product_category'] = 'Insurance Premium'
#######################################################################################
df.loc[df['merchant_name'] == 'ACT Fibernet', 'product_category'] = 'Internet Bill'
df.loc[df['merchant_name'] == 'Airtel Broadband', 'product_category'] = 'Internet Bill'
df.loc[df['merchant_name'] == 'BSNL Broadband', 'product_category'] = 'Internet Bill'
df.loc[df['merchant_name'] == 'Hathway', 'product_category'] = 'Internet Bill'
df.loc[df['merchant_name'] == 'Jio Fiber', 'product_category'] = 'Internet Bill'
########################################################################################
df.loc[df['merchant_name'] == 'Axis Bank', 'product_category'] = 'Loan Repayment'
df.loc[df['merchant_name'] == 'Bajaj Finserv', 'product_category'] = 'Loan Repayment'
df.loc[df['merchant_name'] == 'HDFC Bank', 'product_category'] = 'Loan Repayment'
df.loc[df['merchant_name'] == 'ICICI Bank', 'product_category'] = 'Loan Repayment'
df.loc[df['merchant_name'] == 'SBI', 'product_category'] = 'Loan Repayment'
######################################################################################
df.loc[df['merchant_name'] == 'Airtel', 'product_category'] = 'Mobile Recharge'
df.loc[df['merchant_name'] == 'BSNL', 'product_category'] = 'Mobile Recharge'
df.loc[df['merchant_name'] == 'Idea', 'product_category'] = 'Mobile Recharge'
df.loc[df['merchant_name'] == 'Jio', 'product_category'] = 'Mobile Recharge'
df.loc[df['merchant_name'] == 'Vodafone', 'product_category'] = 'Mobile Recharge'
#################################################################################
df.loc[df['merchant_name'] == 'Carnival Cinemas', 'product_category'] = 'Movie Ticket'
df.loc[df['merchant_name'] == 'Cinepolis', 'product_category'] = 'Movie Ticket'
df.loc[df['merchant_name'] == 'INOX', 'product_category'] = 'Movie Ticket'
df.loc[df['merchant_name'] == 'PVR Cinemas', 'product_category'] = 'Movie Ticket'
df.loc[df['merchant_name'] == 'SPI Cinemas', 'product_category'] = 'Movie Ticket'
####################################################################################
df.loc[df['merchant_name'] == 'Amazon', 'product_category'] = 'Online Shopping'
df.loc[df['merchant_name'] == 'Flipkart', 'product_category'] = 'Online Shopping'
df.loc[df['merchant_name'] == 'Myntra', 'product_category'] = 'Online Shopping'
df.loc[df['merchant_name'] == 'Nykaa', 'product_category'] = 'Online Shopping'
df.loc[df['merchant_name'] == 'Snapdeal', 'product_category'] = 'Online Shopping'
#########################################################################################
df.loc[df['merchant_name'] == 'Airbnb', 'product_category'] = 'Rent Payment'
df.loc[df['merchant_name'] == 'Housing.com', 'product_category'] = 'Rent Payment'
df.loc[df['merchant_name'] == 'Nestaway', 'product_category'] = 'Rent Payment'
df.loc[df['merchant_name'] == 'NoBroker', 'product_category'] = 'Rent Payment'
df.loc[df['merchant_name'] == 'OYO Life', 'product_category'] = 'Rent Payment'
####################################################################################
df.loc[df['merchant_name'] == 'Amazon Prime', 'product_category'] = 'Streaming Service'
df.loc[df['merchant_name'] == 'Hotstar', 'product_category'] = 'Streaming Service'
df.loc[df['merchant_name'] == 'Netflix', 'product_category'] = 'Streaming Service'
df.loc[df['merchant_name'] == 'SonyLIV', 'product_category'] = 'Streaming Service'
df.loc[df['merchant_name'] == 'ZEE5', 'product_category'] = 'Streaming Service'
#########################################################################################
df.loc[df['merchant_name'] == 'Jugnoo', 'product_category'] = 'Taxi Fare'
df.loc[df['merchant_name'] == 'Meru', 'product_category'] = 'Taxi Fare'
df.loc[df['merchant_name'] == 'Rapido', 'product_category'] = 'Taxi Fare'
df.loc[df['merchant_name'] == 'Uber', 'product_category'] = 'Taxi Fare'
df.loc[df['merchant_name'] == 'Ola', 'product_category'] = 'Taxi Fare'

print(df.isna().sum())

df.loc[df['merchant_name'] == 'AbhiBus', 'product_category'] = 'Bus Ticket'
df.loc[df['merchant_name'] == 'Goibibo', 'product_category'] = 'Bus Ticket'
df.loc[df['merchant_name'] == 'MakeMyTrip Bus', 'product_category'] = 'Bus Ticket'
df.loc[df['merchant_name'] == 'Paytm Bus', 'product_category'] = 'Bus Ticket'
df.loc[df['merchant_name'] == 'RedBus', 'product_category'] = 'Bus Ticket'
##############################################################################
df.loc[df['merchant_name'] == "BYJU'S", "product_category"] = 'Education Fee'
df.loc[df['merchant_name'] == 'Coursera', 'product_category'] = 'Education Fee'
df.loc[df['merchant_name'] == 'Udemy', 'product_category'] = 'Education Fee'
df.loc[df['merchant_name'] == 'Unacademy', 'product_category'] = 'Education Feet'
df.loc[df['merchant_name'] == 'Vedantu', 'product_category'] = 'Education Fee'
################################################################################
df.loc[df['merchant_name'] == 'BSES', "product_category"] = 'Electricity Bill'
df.loc[df['merchant_name'] == 'CESC', 'product_category'] = 'Electricity Bill'
df.loc[df['merchant_name'] == 'MSEDCL', 'product_category'] = 'Electricity Bill'
df.loc[df['merchant_name'] == 'Reliance Energy', 'product_category'] = 'Electricity Bill'
df.loc[df['merchant_name'] == 'Tata Power', 'product_category'] = 'Electricity Bill'
####################################################################################
df.loc[df['merchant_name'] == 'Cleartrip', "product_category"] = 'Flight Booking'
df.loc[df['merchant_name'] == 'EaseMyTrip', 'product_category'] = 'Flight Booking'
df.loc[df['merchant_name'] == 'Ixigo', 'product_category'] = 'Flight Booking'
df.loc[df['merchant_name'] == 'MakeMyTrip', 'product_category'] = 'Flight Booking'
df.loc[df['merchant_name'] == 'Yatra', 'product_category'] = 'Flight Booking'
####################################################################################
df.loc[df['merchant_name'] == "Domino's", "product_category"] = 'Food Delivery'
df.loc[df['merchant_name'] == 'Foodpanda', 'product_category'] = 'Food Delivery'
df.loc[df['merchant_name'] == 'Swiggy', 'product_category'] = 'Food Delivery'
df.loc[df['merchant_name'] == 'Uber Eats', 'product_category'] = 'Food Delivery'
df.loc[df['merchant_name'] == 'Zomato', 'product_category'] = 'Food Delivery'
#################################################################################
df.loc[df['merchant_name'] == 'Call of Duty Mobile', "product_category"] = 'Gaming Credits'
df.loc[df['merchant_name'] == 'Free Fire', 'product_category'] = 'Gaming Credits'
df.loc[df['merchant_name'] == 'Minecraft', 'product_category'] = 'Gaming Credits'
df.loc[df['merchant_name'] == 'PUBG Mobile', 'product_category'] = 'Gaming Credits'
df.loc[df['merchant_name'] == 'Roblox', 'product_category'] = 'Gaming Credits'

print(df.isna().sum())

# Group data by 'product_name' and calculate the median for 'product_amount' and 'transaction_fee'
mean_values = df.groupby('product_name')[['product_amount', 'transaction_fee']].mean()

# Function to fill NaN values based on 'product_name'
def fill_na_by_product(row):
  product_name = row['product_name']
  if pd.isnull(row['product_amount']) and product_name in mean_values.index:
    row['product_amount'] = mean_values.loc[product_name]['product_amount']
  if pd.isnull(row['transaction_fee']) and product_name in mean_values.index:
    row['transaction_fee'] = mean_values.loc[product_name]['transaction_fee']
  return row


# Apply the function to fill NaN values
df = df.apply(fill_na_by_product, axis=1)

print(df.isna().sum())

location_mode = df['location'].mode()[0]
# Get the mode
df['location'].fillna(location_mode, inplace=True)

print(df.isna().sum())

# Display information about columns and data types
print(df.info())

df['product_amount'] = df['product_amount'].apply(lambda x: round(x, 2))
df['transaction_fee'] = df['transaction_fee'].apply(lambda x: round(x, 2))

#Data cleaning process and organization of data with Python
df.to_csv('digital payment methods Cleaned.csv', index=False)

import pandas as pd

# Read csv file
df = pd.read_csv("final digital payment methods.csv")

df['product_amount'] = df['product_amount'].apply(lambda x: round(x, 2))
df['transaction_fee'] = df['transaction_fee'].apply(lambda x: round(x, 2))

#Data cleaning process and organization of data with Python
df.to_csv('final digital payment methods 1.csv', index=False)